services:
  mysql-db:
    image: mysql:8.0
    container_name: jailtracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jailtracker
    ports:
      - "3306:3306"